project:
  type: website
  resources:
    - assets/shadoks/


website:
  title: "Adam Arras"
  description: "Research, notes, and teaching"
  favicon: favicon.png
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: CV
        href: CV.qmd
      - text: Blog
        href: blog.qmd
      - text: About
        href: about.qmd
  page-footer:
    left: "© 2026 Adam Arras"
    right: "Last updated: {{< meta date >}}"

date: last-modified
date-format: "MMMM YYYY"

format:
  html:
    theme: slate	
    mathjax: true
    css: styles.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons@1.9.4/css/academicons.min.css">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

